### ISSUE TITLE
Whats is the command to build ?

### ISSUE THREAD

**Issue by debayanMuvi** [PlaceMe-SAS/single-spa-angular-cli-examples#1]
Hi what is the command to build and deploy in server ?

like in angular cli we have ng build --target = production ;
like here what will be the command for final depmoyment ?

**Comment by robinComa** [comment]
Hello @debayanMuvi ,
I recommend to build your CLI projects on this way : 
ng build --prod --output-hashing=media --extract-css=false
And after you have to change the loader with the correct generated files.

To build it on a specific folder of your portal, you can use --output-path= ???
For the portal build, you can refer to the single-spa project

I'm actually work on the global build but it is a big task and it depends of the context.
I think I will propose something next month

**Comment by robinComa** [comment]
Hello, in my new version of the exemple i add the npm run ng:build task : 
https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples/blob/master/package.json#L7
