### ISSUE TITLE
Angular 5 Cli + Angular 1.6

### ISSUE THREAD

**Issue by kumaranbsundar** [PlaceMe-SAS/single-spa-angular-cli-examples#10]
Hi, thx for putting together this sample. It works great. I wanted to run an angular1.5 app alongside the angular5 apps you have setup. Is that possible? So far I have not been having much luck. I added another child app and used the code listed here
https://github.com/CanopyTax/single-spa-examples/tree/master/src/angular1

and in the spa-config file, I have added an additional registerapplication call to register the angular1 spa like below

registerApplication('angular1', () => import('../apps/home2/angular1.app.js'), pathPrefix('/angular1'));
registerApplication(
"menu",
(() => {
const lifecycles = loader({
name: "menu",
selector: "menu-root",
baseHref: "http://s3.us-east-2.amazonaws.com/singlespa/menu"
});
return {
bootstrap: [lifecycles.bootstrap],
mount: [lifecycles.mount],
unmount: [lifecycles.unmount],
unload: [lifecycles.unload],
};
})(),
router.matchRoute("/**", false)
);

When i webpack and run, only the menu app is loading, the angular1 app isn;t loading et all. If i disable the "menu registration above, my ng1 app works. Can the both be wired the way I have setup?

If there is a quick example that shows ng cli app working along side ng1 app, that would be great. Or else if you can provide me with some quick pointers, I would much appreciate it.

**Comment by robinComa** [comment]
Hello, I close the issue, and send feedback [here](https://github.com/PlaceMe-SAS/single-spa-angular-cli/issues/18)
