### ISSUE TITLE
angular 8

### ISSUE THREAD

**Issue by ponnalaxmikanth** [PlaceMe-SAS/single-spa-angular-cli-examples#27]
we have applications build in angular 8, does this work for angular 8 or not? if it works what are all the changes we need to make to work in angular 8?

**Comment by internettrans** [comment]
Hi @ponnalaxmikanth, this repo is no longer active. The single-spa-angular project now supports Angular 8. See https://github.com/joeldenning/coexisting-angular-microfrontends/, https://github.com/CanopyTax/single-spa-angular, and https://single-spa.js.org/docs/ecosystem-angular.

**Comment by ponnalaxmikanth** [comment]
is there any way i can have angular 5, 7 and 8 applications in single portal?

**Comment by internettrans** [comment]
Yes. Not the easiest, but possible. See https://github.com/joeldenning/coexisting-angular-microfrontends/ for an example where three angular applications are coexisting. That example has only angular 8, but you can swap them out for angular 5 or 7 if you want.
