### ISSUE TITLE
Can data shared between apps ?

### ISSUE THREAD

**Issue by lysdyt** [PlaceMe-SAS/single-spa-angular-cli-examples#3]
How can I share data such as tokens between apps?

**Comment by lysdyt** [comment]
close

**Comment by robinComa** [comment]
Do you use single spa props? [like that](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples#configure-your-angular-cli-app-to-be-loaded-by-single-spa)
Is that works?
