### ISSUE TITLE
APP_BASE_HREF Error

### ISSUE THREAD

**Issue by comcy** [PlaceMe-SAS/single-spa-angular-cli-examples#4]
I followed your instructions but I'm getting this error when I run `npm run start`:

`Unhandled Promise rejection: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document. ; Zone: <root> ; Task: Promise.then ; Value: Error: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.`

Building with webpack is ok, but then it stucks...

In the console it shows me something like

`webpack: Compiled successfully.
TypeError: Cannot read property 'indexOf' of undefined
`

**Comment by robinComa** [comment]
Hello @comcy , do you run the demo without modifications?

**Comment by comcy** [comment]
The demo runs successfully. Then I added a custom app. Therefore I followed the instructions and setted it up like the demo apps... Maybe the issue is better placed in the `single-spa-angular-cli` repository?

**Comment by robinComa** [comment]
Your new app has an angular router router? Like the home apps?
If yes, you have to provide a APP_BASE_HREF, like [here](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples/blob/master/apps/home/src/app/app-routing.module.ts#L25)

**Comment by comcy** [comment]
Yes, it worked. Thank you! I'll close this issue... The bad news: the app does not appear. I'm faced with new issues loading a static configuration in the child app... Do you have any suggestions?

**Comment by robinComa** [comment]
What kind of configuration?
On the exemple of the home app, I use assets file, and for all your assets like config file, it should works thanks to the APP_BASE_HREF management.
Are you using another folder than assets/?

**Comment by comcy** [comment]
This is the Error:
```
 Failed to load resource: the server responded with a status of 404 (Not Found)      :8080/app-config/app-config.local.json
```
While `app-config` is a folder located under the assets and declared in `angular-cli.json`. The configuration file `app-config.local.json` is within this folder. The flag `local` is set during the build process with `--env=local` parameter.

**Comment by robinComa** [comment]
Ok, so you have to do the same trick : [here](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples/blob/master/apps/home/src/app/app-routing.module.ts#L25)

If you don't use a router inside your child app, do it on your main module, else, on your router module

Does it works?

**Comment by comcy** [comment]
Not for the moment. I already added the BASE_HREF the last time you adviced me. I did in the separate router module. But still the loading problme. Is there something I missed or do I have to change another file?

**Comment by robinComa** [comment]
Did you try to build with -bh=/yourAppRoute/ ? But I think this will be the same because this arg set the base href this inside the index.html of the child app and it is not used

**Comment by robinComa** [comment]
Maybe the basehref is set after the loading of the config file. A workaround could be the uses of the webpack proxy for dev mode or a global config on the top of the parent app.
