### ISSUE TITLE
Routing in example not working well

### ISSUE THREAD

**Issue by inanbayram** [PlaceMe-SAS/single-spa-angular-cli-examples#5]
I cloned the example localy on my mac and run all the needed commands. The website is opening without any problems. Also the console in the developer window does not show errors. But the strange thing is, that not all buttons (routings) are working well

For example only the button "Route 1" and "Route 2" is working. The other buttons like "Open help (other cli app)", "App 1 (other cli app)" and also the buttons in the "menu" are not working.

I tried the example with chrome, firefox and also safari. On all of them I have this problem? Is this a known issue?

**Comment by robinComa** [comment]
Hello @inanbayram , 
I know...
I try to develop something cool, but, like a newbe I develop it on master... And it is not stable.

This new feature is a router link for Single Spa : [here](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples/blob/master/apps/menu/src/app/app.component.html#L6)

But I have an issue to  run it in AOT mode, so on my master branch I decide to comment the lib : 
[here ](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples/blob/master/apps/menu/src/app/app.module.ts#L18) and [here](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples/blob/master/apps/home/src/app/app.module.ts#L21)

I you un comment it, you have to change the build [here](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples/blob/master/package.json#L9) and add --aot=false for menu and home app.

Sorry for that, next time I will develop on other branch ;-)

**Comment by inanbayram** [comment]
@robinComa thank you for your fast response. It's working fine now :)

**Comment by fergardi** [comment]
Thanks, having the same issue and fixed it.

**Comment by fergardi** [comment]
How to change between apps in JS code instead of using `singleSpaRouterLink` onClick directive?
