### ISSUE TITLE
Hi - did you manage to get a shared service going which could be used by all the other apps?

### ISSUE THREAD

**Issue by nigel-dewar** [PlaceMe-SAS/single-spa-angular-cli-examples#7]

**Comment by nigel-dewar** [comment]
cheers

**Comment by robinComa** [comment]
Hello @nigel-dewar , I tried to achieve it [here](https://github.com/PlaceMe-SAS/single-spa-angular-cli/blob/master/src/module/single-spa.module.ts) but I don't manage to compile with AOT support with ng packager, see this [issue](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples/issues/5)
