### ISSUE TITLE
Question: Active apps not recognising updated routes

### ISSUE THREAD

**Issue by freon27** [PlaceMe-SAS/single-spa-angular-cli-examples#8]
Hi, I'm trying to understand exactly how routing should work when two apps are active.  I've used your project as a great starter but replaced the menu and content with my own CLI apps.  In my case the menu app makes breadbrumbs from the current path.  

I'm trying to set it up so that clicking the breadcrumbs, or navigating within the content app updates the routers of both active apps to be aware of the new location.  I'm not clear on whether this should "just work" or whether I have to manually listen for the single-spa routing events in each application and navigate manually? 

The header will only ever run in a single-spa environment so that's no problem, but we can have many child apps that we have to include which will also run standalone so i have to minimise the changes to them.

I also see that you have a special single spa specific router link in the project but I don't really understand the purpose of it compared to normal router link.

Thanks for any guidance you can give me.

**Comment by freon27** [comment]
Thanks so much for the reply. I'm still not sure I totally understand.... 

As far as I'm aware, there's no event that can be listened to if I use history.pushState so i'm not sure how the applications are supposed to know when the other application updates the history? 

By making the menu app listen for the single spa custom routing event, I'm able to make the breadcrumbs respond to the route changes from the content app. 

I tried making my breadcrumbs use pushState but then the address in the browser updates but the angular router in the content app doesn't know about the change. 

I also tried using navigateToUrl from the link you gave. Again the path updates in the address bar but the angular router does not update content.

Sorry if I'm missing something really obvious. I feel like I'm not totally sure if something is broken or if I'm just expecting behaviour that isn't actually a feature.

**Comment by freon27** [comment]
Also, I'm still not sure what singleSpaRouterLink is for. It doesn't seem to be rendering links for me.

**Comment by robinComa** [comment]
For this issue (router), check here : #5

**Comment by robinComa** [comment]
For your breadcrum, I think you have to listen the url without angular, because it is not part a the menu routes declaration. As says on last post, it is complicated to deal with angular routes on multiple apps on the same view. Because the apps router only know it own routes and not the child app route.
For my sample, I use router only inside the Main apps (not menu or help template)

**Comment by freon27** [comment]
Thanks. I've also been playing with Angular Elements as a potential alternative to Single-SPA and I had to monkey patch pushState to fire a custom event which all of the apps listen to. I'm hoping I can make something similar work for this.
