### ISSUE TITLE
Child applications are not loading because of 404 error

### ISSUE THREAD

**Issue by szilarddoro** [PlaceMe-SAS/single-spa-angular-cli-examples#9]
Hello,

I've started experimenting with this example project to see how I can add my own child applications or modify existing ones, and ran into the following error _(Note: it also applies to all my currently active child applications)_:

> Uncaught Error: 'menu' died in status SKIP_BECAUSE_BROKEN: "Try to load /menu/index.html, status : undefined => undefined"

On the top of the trace, the following error appeared:

> Failed to load resource: the server responded with a status of 404 (Not Found) - :8080/menu/index.html

First of all, I was trying to modify existing apps included in this git project, then decided to rollback to the original version. Neither original version nor my custom solution is able to load any of the child applications.

I don't know if this issue is related to webpack's bundling process, or something like that, but I hope we can get through this easily.

Webpack versions:
- `webpack: ^3.11.0`
- `webpack-dev-server: ^2.9.7`

**Comment by robinComa** [comment]
Do you run 
npm install -g @angular/cli
npm install
npm run ng:build
npm start
?

**Comment by robinComa** [comment]
I think you forgot the npm run ng:build to build all your child app

**Comment by szilarddoro** [comment]
Yes, that was the issue, thanks for your help.

**Comment by robinComa** [comment]
Is it ok now?

**Comment by szilarddoro** [comment]
Yes, thanks 🙂
